language: node_js
node_js: stable
install:
  - npm install
script:
  - hexo g
after_script:
  - cd ./public
  - git init
  - git config user.name "hupoliuguang"
  - git config user.email "2687819306@qq.com"
  - git add .
  - git commit -m "Update Blog By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  - git push --force --quiet "https://${travisGH}@${GH_REF}" master:master
  - git push --force --quiet "https://hupoliuguang:${travisCD1}@${CO_REF}" master:master
branches:
  only:
    - source
env:
  global:
    - GH_REF: github.com/hupoliuguang/hupoliuguang.github.io.git
    - CO_REF: git.dev.tencent.com/hupoliuguang/hupoliuguang.git
