language: node_js
node_js: stable
before_install:
    - export TZ='Asia/Shanghai' # 更改时区
    - npm install hexo-cli -g  # 安装hexo环境
install:
  - npm install
script:
  - hexo clean
  - hexo g
after_script:
  - cd ./public
  - git init
  - git config user.name "hupoliuguang"
  - git config user.email "2687819306@qq.com"
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
  - git push --force --quiet "https://${travisGH}@${GH_REF}" master:master
  - git push --force --quiet "https://hupoliuguang:${travisCD}@${CO_REF}" master:master
branches:
  only:
    - source
env:
  global:
    - GH_REF: github.com/hupoliuguang/hupoliuguang.github.io.git
    - CO_REF: git.coding.net/hupoliuguang/hupoliuguang.coding.me.git
