language: node_js
node_js: stable
notifications:
  email:
    recipients:
      - 2687819306@qq.com
    on_success: always # default: change
    on_failure: always # default: alway
cache:
  directories:
  - node_modules
  yarn: true
before_install:
    - export TZ='Asia/Shanghai' # 更改时区
    - npm install hexo-cli -g  # 安装hexo环境
install:
  - npm install
script:
  - hexo clean
  - hexo g
after_script:
  - cd ./public
  - git init
  - git config --global user.name "hupoliuguang"
  - git config --global user.email "2687819306@qq.com"
  #- git add .
  #- git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
  #- git tag v0.0.$TRAVIS_BUILD_NUMBER -a -m "Auto Taged By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # Github Pages
  #- git push --force --quiet "https://${travisGH}@${GH_REF}" master:master --tags
  # Coding Pages
  #- git push --force --quiet "https://hupoliuguang:${travisCD}@${CO_REF}" master:master --tags
  #- sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - hexo deploy
  

  
branches:
  only:
    - source
env:
  global:
    - GH_REF: github.com/hupoliuguang/hupoliuguang.github.io.git
    - CO_REF: git.dev.tencent.com/hupoliuguang/hupoliuguang.git
